# Default values for celfahr-chart.
# You can override these values in the helm command or in a separate values.yaml file.

# Deployment configuration
replicaCount: 1
image:
  repository: valentingarciairiart/celfahr
  tag: v3
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Ingress configuration
ingress:
  name: ingress-helmcel
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: valenceltest.modelodevops.sociuschile.cl
      paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name: celfahr-service
              port:
                number: 80
  

# Service configuration
service:
  name: celfahr-service
  type: ClusterIP
  port: 80
  targetPort: 3000

# Deployment configuration
namespace: valenhelm
containerPort: 3000
containerName: celfahr-container
deploymentName: app-celfahr
