# Default values for celfahr-chart.
# You can override these values in the helm command or in a separate values.yaml file.

# Deployment configuration
deployment: 
  metadata:
    name: app-celfahr
  spec:
    replicaCount: 1
    template:
      spec:
        containers: 
          name: celfahr-container
          image:
            repository: valentingarciairiart/celfahr
            tag: v1.1
            pullPolicy: Always
          ports:
            containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

# Service configuration
service:
  metadata:
    name: helmfahr-servicex2
  spec:
    type: ClusterIP
    ports:
        port: 80
        targetPort: 3000

# Ingress configuration
ingress:
  enabled: true
  metadata:
    name: nginx-helmcel
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  spec:
    ingressClassName: nginx
    tls:
      - secretName: helmtest-socius
        hosts:
          - valhelmtest.modelodevops.sociuschile.cl
    rules:
      - host: valhelmtest.modelodevops.sociuschile.cl
        http:
          paths:
            - path: /(.*)   # Ruta absoluta válida
              pathType: Prefix  # Opción válida para pathType
