# Default values for celfahr-chart.
# You can override these values in the helm command or in a separate values.yaml file.

# Deployment configuration
replicaCount: 1
image:
  repository: valentingarciairiart/celfahr
  tag: v3
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 500m
    memory: 512Mi

# Ingress configuration
ingress:
  host: valenceltest.modelodevops.sociuschile.cl
  secretName: valentincelsius-secret-socius
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  paths:
    - path: /?(.*)
      pathType: Prefix
      backend:
        service:
          name: celfahr-service  # Nombre del servicio para el Ingress
          port:
            number: 80
  className: nginx  # Variable para la clase del Ingress

# Service configuration
service:
  name: celfahr-service
  type: ClusterIP
  port: 80
  targetPort: 3000

# Deployment configuration
namespace: valenhelm
containerPort: 3000
containerName: celfahr-container
deploymentName: app-celfahr
