# Default values for celfahr-chart.
# You can override these values in the helm command or in a separate values.yaml file.

# Deployment configuration
replicaCount: 1
image:
  repository: valentingarciairiart/celfahr
  tag: v4
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Ingress configuration
ingress:
  enabled: true
  name: nginx-helmcel
  ingressClassName: nginx
  host: valhelmtest.modelodevops.sociuschile.cl
  path: /(.*)   # Ruta absoluta válida
  pathType: Prefix  # Opción válida para pathType
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  

# Service configuration
service:
  name: helmfahr-servicex
  type: ClusterIP
  port: 80
  targetPort: 3000

# Deployment configuration
namespace: valenhelm
containerPort: 3000
containerName: celfahr-container
deploymentName: app-celfahr
secretName: helmtest-socius
certName: letsencrypt-staging
rewriteTarget: /$1
