# Default values for celfahr-chart.
# You can override these values in the helm command or in a separate values.yaml file.

# Deployment configuration
replicaCount: 1
containerPort: 3000
containerName: celfahr-container
deploymentName: app-celfahr
image:
  repository: valentingarciairiart/celfahr
  tag: v9
  pullPolicy: Always
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Ingress configuration
ingress:
  enabled: true
  metadata:
    name: nginx-helmcel
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  spec:
    ingressClassName: nginx
    tls:
      - secretName: helmtest-socius
        hosts:
          - valhelmtest.modelodevops.sociuschile.cl
    rules:
      - host: valhelmtest.modelodevops.sociuschile.cl
        http:
          paths:
            - path: /(.*)   # Ruta absoluta válida
              pathType: Prefix  # Opción válida para pathType

# Service configuration
service:
  name: helmfahr-servicex2
  type: ClusterIP
  port: 80
  targetPort: 3000

