apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.metadata.name }}
spec:
  replicas: {{ .Values.deployment.spec.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.metadata.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.spec.template.spec.containers.name }}
          image: "{{ .Values.deployment.spec.template.spec.containers.image.repository }}:{{ .Values.deployment.spec.template.spec.containers.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.spec.template.spec.containers.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.spec.template.spec.containers.ports.containerPort }}
          resources:
            limits:
              cpu: {{ .Values.deployment.spec.template.spec.containers.resources.limits.cpu }}
              memory: {{ .Values.deployment.spec.template.spec.containers.resources.limits.memory }}
            requests:
              cpu: {{ .Values.deployment.spec.template.spec.containers.resources.cpu }}
              memory: {{ .Values.deployment.spec.template.spec.containers.resources.memory }}