apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.metadata.name }}
  annotations:
{{- range $key, $value := .Values.ingress.metadata.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.spec.ingressClassName }}
  tls:
{{- range $tlsConfig := .Values.ingress.spec.tls }}
    - secretName: {{ $tlsConfig.secretName }}
      hosts:
{{- range $host := $tlsConfig.hosts }}
        - {{ $host | quote }}
{{- end }}
{{- end }}
  rules:
{{- range $rule := .Values.ingress.spec.rules }}
    - host: {{ $rule.host | quote }}
      http:
        paths:
{{- range $path := $rule.http.paths }}
          - path: {{ $path.path | quote }}
            pathType: {{ $path.pathType | quote }}
            backend:
              service:
                name: {{ $.Values.service.metadata.name }}
                port:
                  number: {{ $.Values.service.spec.ports.port }}
{{- end }}
{{- end }}

