apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
spec:
  type: {{ .Values.service.spec.type }}
  ports:
    - port: {{ .Values.service.spec.ports.port }}
      targetPort: {{ .Values.service.spec.ports.targetPort }}
  selector:
    app: {{ .Values.deploymentName }}